import type { ReactNode } from "react";

export const metadata = {
  title: "E2E Test Site",
  description: "Generated by siteforge",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body style={{ fontFamily: "system-ui, sans-serif", margin: 0 }}>
        <header style={{ padding: 16, borderBottom: "1px solid #eee" }}>
          <strong>E2E Test Site</strong>
          <nav style={{ marginTop: 8 }}>
          <a href="/" style={{ marginRight: 16 }}>Home</a>
          <a href="/products" style={{ marginRight: 16 }}>Products</a>
          <a href="/checkout" style={{ marginRight: 16 }}>Checkout</a>
          <a href="/contact" style={{ marginRight: 16 }}>Contact</a>
          <a href="/privacy" style={{ marginRight: 16 }}>Privacy</a>
          <a href="/terms-conditions" style={{ marginRight: 16 }}>Terms & Conditions</a>
          <a href="/login" style={{ marginRight: 16 }}>Login</a>
          </nav>
        </header>
        <main style={{ padding: 24 }}>{children}</main>
      </body>
    </html>
  );
}
