import { execFile } from "node:child_process";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { promisify } from "node:util";

const execFileAsync = promisify(execFile);

interface BlueprintSelections {
    selectedPages?: string[];
    selectedFeatures?: string[];
    selectedIntegrations?: string[];
    selectedLocales?: string[];
    selectedRoles?: string[];
    selectedBrandTones?: string[];
    selectedVisualStyles?: string[];
    selectedContentModels?: string[];
    selectedSEOFocuses?: string[];
}

interface Blueprint {
    id?: string;
    createdAt?: string;
    projectName?: string;
    slug?: string;
    selections?: BlueprintSelections;
}

interface ScaffoldOptions {
    blueprintPath: string;
    outRoot?: string;
    initGit?: boolean;
}

const DEFAULT_OUT_ROOT = "/Users/waelio/Code/GitHub/waelio/siteforge/sites";

function slugify(value: string): string {
    return value
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, "-")
        .replace(/^-+|-+$/g, "")
        || "site";
}

function pageToRoute(name: string): string {
    const trimmed = name.trim();
    if (!trimmed || trimmed.toLowerCase() === "home") return "/";
    return "/" + slugify(trimmed);
}

function pagePath(route: string): string {
    if (route === "/") return "app/page.tsx";
    return `app${route}/page.tsx`;
}

async function writeFileEnsured(filePath: string, content: string): Promise<void> {
    await mkdir(path.dirname(filePath), { recursive: true });
    await writeFile(filePath, content, "utf8");
}

function frontendPackageJson(name: string): string {
    return JSON.stringify(
        {
            name: `${name}-frontend`,
            version: "0.0.1",
            private: true,
            scripts: {
                dev: "next dev -p 3001",
                build: "next build",
                start: "next start -p 3001",
                lint: "next lint",
            },
            dependencies: {
                next: "^14.2.0",
                react: "^18.3.1",
                "react-dom": "^18.3.1",
            },
            devDependencies: {
                typescript: "^5.4.0",
                "@types/node": "^20.0.0",
                "@types/react": "^18.3.0",
                "@types/react-dom": "^18.3.0",
            },
        },
        null,
        2,
    );
}

const NEXT_TSCONFIG = `{
  "compilerOptions": {
    "target": "ES2020",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": false,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [{ "name": "next" }],
    "baseUrl": ".",
    "paths": { "@/*": ["./*"] }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx"],
  "exclude": ["node_modules"]
}
`;

const NEXT_CONFIG = `/** @type {import('next').NextConfig} */
const nextConfig = { reactStrictMode: true };
module.exports = nextConfig;
`;

const NEXT_ENV_DTS = `/// <reference types="next" />
/// <reference types="next/image-types/global" />
`;

function rootLayout(name: string, pages: { name: string; route: string }[]): string {
    const navItems = pages
        .map((p) => `<a href="${p.route}" style={{ marginRight: 16 }}>${p.name}</a>`)
        .join("\n          ");

    return `import type { ReactNode } from "react";

export const metadata = {
  title: "${name}",
  description: "Generated by waelio/cli + siteforge",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body style={{ fontFamily: "system-ui, sans-serif", margin: 0 }}>
        <header style={{ padding: 16, borderBottom: "1px solid #eee" }}>
          <strong>${name}</strong>
          <nav style={{ marginTop: 8 }}>
          ${navItems}
          </nav>
        </header>
        <main style={{ padding: 24 }}>{children}</main>
      </body>
    </html>
  );
}
`;
}

function pageComponent(pageName: string, projectName: string): string {
    const isHome = pageName.toLowerCase() === "home" || pageName === "/";
    const heading = isHome ? projectName : pageName;
    return `export default function Page() {
  return (
    <section>
      <h1>${heading}</h1>
      <p>Generated ${pageName} page.</p>
    </section>
  );
}
`;
}

function backendPackageJson(name: string): string {
    return JSON.stringify(
        {
            name: `${name}-backend`,
            version: "0.0.1",
            private: true,
            scripts: {
                start: "node dist/main.js",
                "start:dev": "ts-node-dev --respawn src/main.ts",
                build: "tsc -p tsconfig.json",
            },
            dependencies: {
                "@nestjs/common": "^10.3.0",
                "@nestjs/core": "^10.3.0",
                "@nestjs/platform-express": "^10.3.0",
                "reflect-metadata": "^0.2.0",
                rxjs: "^7.8.0",
            },
            devDependencies: {
                "@types/node": "^20.0.0",
                "ts-node-dev": "^2.0.0",
                typescript: "^5.4.0",
            },
        },
        null,
        2,
    );
}

const NEST_TSCONFIG = `{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es2021",
    "outDir": "./dist",
    "rootDir": "./src",
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "esModuleInterop": true,
    "strict": true,
    "skipLibCheck": true
  },
  "include": ["src/**/*.ts"],
  "exclude": ["node_modules", "dist"]
}
`;

function nestMain(modules: string[]): string {
    const moduleList = modules.map((m) => `"${m}"`).join(", ");
    return `import "reflect-metadata";
import { NestFactory } from "@nestjs/core";
import { AppModule } from "./app.module.js";

async function bootstrap() {
  const app = await NestFactory.create(AppModule);
  app.enableCors();
  const port = Number(process.env.PORT ?? 3002);
  await app.listen(port);
  console.log(\`backend listening on http://localhost:\${port}\`);
  console.log("modules:", [${moduleList}]);
}
bootstrap();
`;
}

const NEST_APP_MODULE = `import { Module } from "@nestjs/common";
import { HealthController } from "./health.controller.js";

@Module({
  controllers: [HealthController],
})
export class AppModule {}
`;

const NEST_HEALTH_CONTROLLER = `import { Controller, Get } from "@nestjs/common";

@Controller("health")
export class HealthController {
  @Get()
  ok() {
    return { status: "ok", at: new Date().toISOString() };
  }
}
`;

function rootReadme(name: string, slug: string, blueprint: Blueprint): string {
    const sel = blueprint.selections ?? {};
    const list = (xs?: string[]) =>
        xs && xs.length ? xs.map((x) => `- ${x}`).join("\n") : "_(none)_";
    return `# ${name}

Generated by **waelio/cli** from a siteforge blueprint.

- **Slug:** \`${slug}\`
- **Generated:** ${new Date().toISOString()}

## Layout

- \`frontend/\` — Next.js app (port 3001)
- \`backend/\` — NestJS app (port 3002)

## Run

\`\`\`bash
cd frontend && npm install && npm run dev
cd ../backend && npm install && npm run start:dev
\`\`\`

## Blueprint selections

### Pages
${list(sel.selectedPages)}

### Features
${list(sel.selectedFeatures)}

### Integrations
${list(sel.selectedIntegrations)}

### Locales
${list(sel.selectedLocales)}

### Roles
${list(sel.selectedRoles)}
`;
}

const ROOT_GITIGNORE = `node_modules/
dist/
.next/
.env
.env.local
*.log
`;

export interface ScaffoldResult {
    slug: string;
    outDir: string;
    pageCount: number;
}

export async function scaffold(options: ScaffoldOptions): Promise<ScaffoldResult> {
    const raw = await readFile(options.blueprintPath, "utf8");
    const blueprint = JSON.parse(raw) as Blueprint;

    const projectName = blueprint.projectName?.trim() || "Siteforge Project";
    const slug = slugify(blueprint.slug || projectName);
    const outRoot = options.outRoot || DEFAULT_OUT_ROOT;
    const outDir = path.join(outRoot, slug);

    const sel = blueprint.selections ?? {};
    const pageNames = Array.from(
        new Set([
            "Home",
            ...(sel.selectedPages ?? []),
        ]),
    );
    const pages = pageNames.map((name) => ({ name, route: pageToRoute(name) }));

    // Frontend
    await writeFileEnsured(
        path.join(outDir, "frontend/package.json"),
        frontendPackageJson(slug),
    );
    await writeFileEnsured(
        path.join(outDir, "frontend/tsconfig.json"),
        NEXT_TSCONFIG,
    );
    await writeFileEnsured(
        path.join(outDir, "frontend/next.config.js"),
        NEXT_CONFIG,
    );
    await writeFileEnsured(
        path.join(outDir, "frontend/next-env.d.ts"),
        NEXT_ENV_DTS,
    );
    await writeFileEnsured(
        path.join(outDir, "frontend/app/layout.tsx"),
        rootLayout(projectName, pages),
    );

    for (const page of pages) {
        await writeFileEnsured(
            path.join(outDir, "frontend", pagePath(page.route)),
            pageComponent(page.name, projectName),
        );
    }

    // Backend
    const features = sel.selectedFeatures ?? [];
    const modules = ["Health", ...features];
    await writeFileEnsured(
        path.join(outDir, "backend/package.json"),
        backendPackageJson(slug),
    );
    await writeFileEnsured(
        path.join(outDir, "backend/tsconfig.json"),
        NEST_TSCONFIG,
    );
    await writeFileEnsured(
        path.join(outDir, "backend/src/main.ts"),
        nestMain(modules),
    );
    await writeFileEnsured(
        path.join(outDir, "backend/src/app.module.ts"),
        NEST_APP_MODULE,
    );
    await writeFileEnsured(
        path.join(outDir, "backend/src/health.controller.ts"),
        NEST_HEALTH_CONTROLLER,
    );

    // Root
    await writeFileEnsured(
        path.join(outDir, "README.md"),
        rootReadme(projectName, slug, blueprint),
    );
    await writeFileEnsured(
        path.join(outDir, ".gitignore"),
        ROOT_GITIGNORE,
    );
    await writeFileEnsured(
        path.join(outDir, "blueprint.json"),
        JSON.stringify(blueprint, null, 2),
    );

    if (options.initGit !== false) {
        try {
            await execFileAsync("git", ["init", "-q"], { cwd: outDir });
            await execFileAsync("git", ["add", "."], { cwd: outDir });
            await execFileAsync(
                "git",
                ["commit", "-q", "-m", "scaffold from siteforge blueprint"],
                {
                    cwd: outDir,
                    env: {
                        ...process.env,
                        GIT_AUTHOR_NAME: process.env.GIT_AUTHOR_NAME ?? "waelio-cli",
                        GIT_AUTHOR_EMAIL:
                            process.env.GIT_AUTHOR_EMAIL ?? "cli@waelio.dev",
                        GIT_COMMITTER_NAME:
                            process.env.GIT_COMMITTER_NAME ?? "waelio-cli",
                        GIT_COMMITTER_EMAIL:
                            process.env.GIT_COMMITTER_EMAIL ?? "cli@waelio.dev",
                    },
                },
            );
        } catch (err) {
            // Non-fatal: leave folder unversioned if git init fails.
            console.warn(
                `git init skipped: ${err instanceof Error ? err.message : String(err)}`,
            );
        }
    }

    return { slug, outDir, pageCount: pages.length };
}
