import { execFile } from "node:child_process";
import { mkdir, readFile, stat, writeFile } from "node:fs/promises";
import path from "node:path";
import { promisify } from "node:util";
import { fileURLToPath } from "node:url";

const execFileAsync = promisify(execFile);

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const TEMPLATES_DIR = path.resolve(__dirname, "../../templates/multiframework");

export interface BlueprintSelections {
    selectedPages?: string[];
    selectedFeatures?: string[];
    selectedIntegrations?: string[];
    selectedLocales?: string[];
    selectedRoles?: string[];
    selectedBrandTones?: string[];
    selectedVisualStyles?: string[];
    selectedContentModels?: string[];
    selectedSEOFocuses?: string[];
}

export interface Blueprint {
    id?: string;
    createdAt?: string;
    projectName?: string;
    slug?: string;
    selections?: BlueprintSelections;
}

export interface ScaffoldOptions {
    blueprintPath: string;
    outRoot?: string;
    initGit?: boolean;
}

export interface ScaffoldFromBlueprintOptions {
    blueprint: Blueprint;
    outRoot?: string;
    initGit?: boolean;
}

const DEFAULT_OUT_ROOT = "/Users/waelio/Code/GitHub/waelio/siteforge/public-sites";

function slugify(value: string): string {
    return value
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, "-")
        .replace(/^-+|-+$/g, "")
        || "site";
}

function pascalCase(str: string): string {
    return slugify(str).split("-").map(w => w.charAt(0).toUpperCase() + w.slice(1)).join("");
}

function camelCase(str: string): string {
    const p = pascalCase(str);
    return p ? p.charAt(0).toLowerCase() + p.slice(1) : "";
}

function pageToRoute(name: string): string {
    const trimmed = name.trim();
    if (!trimmed || trimmed.toLowerCase() === "home") return "/";
    return "/" + slugify(trimmed);
}

function pagePath(route: string): string {
    if (route === "/") return "app/page.tsx";
    return `app${route}/page.tsx`;
}

async function writeFileEnsured(filePath: string, content: string): Promise<void> {
    await mkdir(path.dirname(filePath), { recursive: true });
    await writeFile(filePath, content, "utf8");
}

function frontendPackageJson(name: string): string {
    return JSON.stringify(
        {
            name: `${name}-frontend`,
            version: "0.0.1",
            private: true,
            scripts: {
                dev: "next dev -p 3001",
                build: "next build",
                start: "next start -p 3001",
                lint: "next lint",
            },
            dependencies: {
                next: "^14.2.0",
                react: "^18.3.1",
                "react-dom": "^18.3.1",
            },
            devDependencies: {
                typescript: "^5.4.0",
                "@types/node": "^20.0.0",
                "@types/react": "^18.3.0",
                "@types/react-dom": "^18.3.0",
            },
        },
        null,
        2,
    );
}

const NEXT_TSCONFIG = `{
  "compilerOptions": {
    "target": "ES2020",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": false,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [{ "name": "next" }],
    "baseUrl": ".",
    "paths": { "@/*": ["./*"] }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx"],
  "exclude": ["node_modules"]
}
`;

const NEXT_CONFIG = `/** @type {import('next').NextConfig} */
const nextConfig = { reactStrictMode: true };
module.exports = nextConfig;
`;

const NEXT_ENV_DTS = `/// <reference types="next" />
/// <reference types="next/image-types/global" />
`;

function rootLayout(name: string, pages: { name: string; route: string }[]): string {
    const navItems = pages
        .map((p) => `<a href="${p.route}" style={{ marginRight: 16 }}>${p.name}</a>`)
        .join("\n          ");

    return `import type { ReactNode } from "react";

export const metadata = {
  title: "${name}",
  description: "Generated by waelio/cli + siteforge",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body style={{ fontFamily: "system-ui, sans-serif", margin: 0 }}>
        <header style={{ padding: 16, borderBottom: "1px solid #eee" }}>
          <strong>${name}</strong>
          <nav style={{ marginTop: 8 }}>
          ${navItems}
          </nav>
        </header>
        <main style={{ padding: 24 }}>{children}</main>
      </body>
    </html>
  );
}
`;
}

function pageComponent(pageName: string, projectName: string): string {
    const isHome = pageName.toLowerCase() === "home" || pageName === "/";
    const heading = isHome ? projectName : pageName;
    return `export default function Page() {
  return (
    <section>
      <h1>${heading}</h1>
      <p>Generated ${pageName} page.</p>
    </section>
  );
}
`;
}

function backendPackageJson(name: string): string {
    return JSON.stringify(
        {
            name: `${name}-backend`,
            version: "0.0.1",
            private: true,
            scripts: {
                start: "node dist/main.js",
                "start:dev": "ts-node-dev --respawn src/main.ts",
                build: "tsc -p tsconfig.json",
            },
            dependencies: {
                "@nestjs/common": "^10.3.0",
                "@nestjs/core": "^10.3.0",
                "@nestjs/platform-express": "^10.3.0",
                "reflect-metadata": "^0.2.0",
                rxjs: "^7.8.0",
            },
            devDependencies: {
                "@types/node": "^20.0.0",
                "ts-node-dev": "^2.0.0",
                typescript: "^5.4.0",
            },
        },
        null,
        2,
    );
}

const NEST_TSCONFIG = `{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es2021",
    "outDir": "./dist",
    "rootDir": "./src",
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "esModuleInterop": true,
    "strict": true,
    "skipLibCheck": true
  },
  "include": ["src/**/*.ts"],
  "exclude": ["node_modules", "dist"]
}
`;

function nestMain(modules: string[]): string {
    const moduleList = modules.map((m) => `"${m}"`).join(", ");
    return `import "reflect-metadata";
import { NestFactory } from "@nestjs/core";
import { AppModule } from "./app.module.js";

async function bootstrap() {
  const app = await NestFactory.create(AppModule);
  app.enableCors();
  const port = Number(process.env.PORT ?? 3002);
  await app.listen(port);
  console.log(\`backend listening on http://localhost:\${port}\`);
  console.log("modules:", [${moduleList}]);
}
bootstrap();
`;
}

function nestAppModule(features: string[]): string {
    const imports = features.map(f => {
        const routeName = slugify(f);
        const pName = pascalCase(f);
        return `import { ${pName}Module } from "./${routeName}/${routeName}.module.js";`;
    }).join("\n");
    
    const moduleNames = features.map(f => `${pascalCase(f)}Module`);
    const importsArray = moduleNames.length > 0 ? `\n    ${moduleNames.join(",\n    ")}\n  ` : "";

    return `import { Module } from "@nestjs/common";
import { HealthController } from "./health.controller.js";
${imports}

@Module({
  imports: [${importsArray}],
  controllers: [HealthController],
})
export class AppModule {}
`;
}

function nestFeatureService(name: string): string {
    const pName = pascalCase(name);
    const className = `${pName}Service`;
    return `import { Injectable } from "@nestjs/common";

@Injectable()
export class ${className} {
  get${pName}() {
    return { message: "This action returns a ${name}" };
  }
}
`;
}

function nestFeatureController(name: string): string {
    const pName = pascalCase(name);
    const className = `${pName}Controller`;
    const serviceName = `${pName}Service`;
    const serviceVar = `${camelCase(name)}Service`;
    const routeName = slugify(name);
    return `import { Controller, Get } from "@nestjs/common";
import { ${serviceName} } from "./${routeName}.service.js";

@Controller("${routeName}")
export class ${className} {
  constructor(private readonly ${serviceVar}: ${serviceName}) {}

  @Get()
  get() {
    return this.${serviceVar}.get${pName}();
  }
}
`;
}

function nestFeatureModule(name: string): string {
    const pName = pascalCase(name);
    const className = `${pName}Module`;
    const controllerName = `${pName}Controller`;
    const serviceName = `${pName}Service`;
    const routeName = slugify(name);
    return `import { Module } from "@nestjs/common";
import { ${controllerName} } from "./${routeName}.controller.js";
import { ${serviceName} } from "./${routeName}.service.js";

@Module({
  controllers: [${controllerName}],
  providers: [${serviceName}],
})
export class ${className} {}
`;
}

const NEST_HEALTH_CONTROLLER = `import { Controller, Get } from "@nestjs/common";

@Controller("health")
export class HealthController {
  @Get()
  ok() {
    return { status: "ok", at: new Date().toISOString() };
  }
}
`;

function rootReadme(name: string, slug: string, blueprint: Blueprint): string {
    const sel = blueprint.selections ?? {};
    const list = (xs?: string[]) =>
        xs && xs.length ? xs.map((x) => `- ${x}`).join("\n") : "_(none)_";
    return `# ${name}

Generated by **waelio/cli** from a siteforge blueprint.

- **Slug:** \`${slug}\`
- **Generated:** ${new Date().toISOString()}

## Layout

- \`frontend/\` — Next.js app (port 3001)
- \`backend/\` — NestJS app (port 3002)

## Run

\`\`\`bash
cd frontend && npm install && npm run dev
cd ../backend && npm install && npm run start:dev
\`\`\`

## Blueprint selections

### Pages
${list(sel.selectedPages)}

### Features
${list(sel.selectedFeatures)}

### Integrations
${list(sel.selectedIntegrations)}

### Locales
${list(sel.selectedLocales)}

### Roles
${list(sel.selectedRoles)}
`;
}

const ROOT_GITIGNORE = `node_modules/
dist/
.next/
.env
.env.local
*.log
`;

export interface ScaffoldResult {
    slug: string;
    outDir: string;
    pageCount: number;
}

async function pathExists(target: string): Promise<boolean> {
    try {
        await stat(target);
        return true;
    } catch {
        return false;
    }
}

async function uniqueOutDir(outRoot: string, slug: string): Promise<string> {
    const base = path.join(outRoot, slug);
    if (!(await pathExists(base))) return base;
    for (let i = 2; i < 1000; i++) {
        const candidate = path.join(outRoot, `${slug}-${i}`);
        if (!(await pathExists(candidate))) return candidate;
    }
    throw new Error(`Unable to find a free output directory for slug "${slug}"`);
}

export async function scaffoldFromBlueprint(
    options: ScaffoldFromBlueprintOptions,
): Promise<ScaffoldResult> {
    const blueprint = options.blueprint;
    const projectName = blueprint.projectName?.trim() || "Siteforge Project";
    const slugBase = slugify(blueprint.slug || projectName);
    const outRoot = options.outRoot || DEFAULT_OUT_ROOT;
    const outDir = await uniqueOutDir(outRoot, slugBase);
    const slug = path.basename(outDir);

    return writeScaffold(blueprint, projectName, slug, outDir, options.initGit);
}

export async function scaffold(options: ScaffoldOptions): Promise<ScaffoldResult> {
    const raw = await readFile(options.blueprintPath, "utf8");
    const blueprint = JSON.parse(raw) as Blueprint;

    return scaffoldFromBlueprint({
        blueprint,
        outRoot: options.outRoot,
        initGit: options.initGit,
    });
}

async function writeScaffold(
    blueprint: Blueprint,
    projectName: string,
    slug: string,
    outDir: string,
    initGit: boolean | undefined,
): Promise<ScaffoldResult> {

    const sel = blueprint.selections ?? {};
    const pageNames = Array.from(
        new Set([
            "Home",
            ...(sel.selectedPages ?? []),
        ]),
    );
    const pages = pageNames.map((name) => ({ name, route: pageToRoute(name) }));

    const integrations = (sel.selectedIntegrations ?? []).map(x => x.toLowerCase());
    let framework: "next" | "vue" | "react" | "svelte" | "angular" = "next";
    
    if (integrations.includes("vue")) framework = "vue";
    else if (integrations.includes("svelte")) framework = "svelte";
    else if (integrations.includes("angular")) framework = "angular";
    else if (integrations.includes("react") && !integrations.includes("next.js")) framework = "react";

    if (framework === "next") {
        // Next.js Frontend
        await writeFileEnsured(
            path.join(outDir, "frontend/package.json"),
            frontendPackageJson(slug),
        );
        await writeFileEnsured(
            path.join(outDir, "frontend/tsconfig.json"),
            NEXT_TSCONFIG,
        );
        await writeFileEnsured(
            path.join(outDir, "frontend/next.config.js"),
            NEXT_CONFIG,
        );
        await writeFileEnsured(
            path.join(outDir, "frontend/next-env.d.ts"),
            NEXT_ENV_DTS,
        );
        await writeFileEnsured(
            path.join(outDir, "frontend/app/layout.tsx"),
            rootLayout(projectName, pages),
        );

        for (const page of pages) {
            await writeFileEnsured(
                path.join(outDir, "frontend", pagePath(page.route)),
                pageComponent(page.name, projectName),
            );
        }
    } else {
        // Multi-framework Frontend
        try {
            const pkgPath = path.join(TEMPLATES_DIR, `package.${framework}.json`);
            let pkgData = await readFile(pkgPath, "utf8");
            
            // Render package.json
            pkgData = pkgData.replace(/"name":\s*"[^"]+"/, `"name": "${slug}-frontend"`);
            await writeFileEnsured(path.join(outDir, "frontend/package.json"), pkgData);

            const extMap: Record<string, string> = {
                vue: "vue",
                react: "tsx",
                svelte: "svelte",
                angular: "component.ts"
            };
            const ext = extMap[framework];
            const tplPath = path.join(TEMPLATES_DIR, `index.${ext}`);
            let tplData = await readFile(tplPath, "utf8");

            // Render template placeholders
            tplData = tplData
                .replace(/\{\{\s*title\s*\}\}/g, projectName)
                .replace(/\{\{\s*email\s*\}\}/g, `${slug}@example.com`)
                .replace(/\{\{\s*description\s*\}\}/g, `Generated frontend for ${projectName}`);

            // For simplicity, just create an App/index file since the templates are single components
            const srcPath = path.join(outDir, "frontend/src", `App.${ext}`);
            await writeFileEnsured(srcPath, tplData);
        } catch (e) {
            console.warn(`Failed to scaffold ${framework} frontend, falling back to empty dir: ${e}`);
        }
    }
    // Backend
    const features = sel.selectedFeatures ?? [];
    const modules = ["Health", ...features];
    await writeFileEnsured(
        path.join(outDir, "backend/package.json"),
        backendPackageJson(slug),
    );
    await writeFileEnsured(
        path.join(outDir, "backend/tsconfig.json"),
        NEST_TSCONFIG,
    );
    await writeFileEnsured(
        path.join(outDir, "backend/src/main.ts"),
        nestMain(modules),
    );
    await writeFileEnsured(
        path.join(outDir, "backend/src/app.module.ts"),
        nestAppModule(features),
    );
    await writeFileEnsured(
        path.join(outDir, "backend/src/health.controller.ts"),
        NEST_HEALTH_CONTROLLER,
    );

    for (const feature of features) {
        const routeName = slugify(feature);
        const featureDir = path.join(outDir, "backend/src", routeName);
        await writeFileEnsured(
            path.join(featureDir, `${routeName}.service.ts`),
            nestFeatureService(feature)
        );
        await writeFileEnsured(
            path.join(featureDir, `${routeName}.controller.ts`),
            nestFeatureController(feature)
        );
        await writeFileEnsured(
            path.join(featureDir, `${routeName}.module.ts`),
            nestFeatureModule(feature)
        );
    }

    // Root
    await writeFileEnsured(
        path.join(outDir, "README.md"),
        rootReadme(projectName, slug, blueprint),
    );
    await writeFileEnsured(
        path.join(outDir, ".gitignore"),
        ROOT_GITIGNORE,
    );
    await writeFileEnsured(
        path.join(outDir, "blueprint.json"),
        JSON.stringify(blueprint, null, 2),
    );

    if (initGit !== false) {
        try {
            await execFileAsync("git", ["init", "-q"], { cwd: outDir });
            await execFileAsync("git", ["add", "."], { cwd: outDir });
            await execFileAsync(
                "git",
                ["commit", "-q", "-m", "scaffold from siteforge blueprint"],
                {
                    cwd: outDir,
                    env: {
                        ...process.env,
                        GIT_AUTHOR_NAME: process.env.GIT_AUTHOR_NAME ?? "waelio-cli",
                        GIT_AUTHOR_EMAIL:
                            process.env.GIT_AUTHOR_EMAIL ?? "cli@waelio.dev",
                        GIT_COMMITTER_NAME:
                            process.env.GIT_COMMITTER_NAME ?? "waelio-cli",
                        GIT_COMMITTER_EMAIL:
                            process.env.GIT_COMMITTER_EMAIL ?? "cli@waelio.dev",
                    },
                },
            );
        } catch (err) {
            // Non-fatal: leave folder unversioned if git init fails.
            console.warn(
                `git init skipped: ${err instanceof Error ? err.message : String(err)}`,
            );
        }
    }

    return { slug, outDir, pageCount: pages.length };
}
